### PR TITLE
User friendly api key

### PR DESCRIPTION
**Pull request by montaguegabe**
Tested and working.  Right now I am using `~/.parsagon_profile`, since I thought using a hidden file in the home directory is more common, but if you feel strongly that it should be somewhere else I can do that too.

I added a `setup` command as well in case a user needs to change their API key once they already have one.

### CODE REVIEW

**Comment by Sand1929** [comment]
Closing and reopening to merge into staging instead of main

**Comment by montaguegabe** [comment]
If you reopen then I can edit and set the upstream to staging

**Comment by montaguegabe** [comment]
Or maybe I can

**Comment by montaguegabe** [comment]
Oh looks like it is already merged

**Pull request closed without merging**
