### PR TITLE
Add run ability

### PR DESCRIPTION
**Pull request by montaguegabe**
Still in the process of debugging.

Let me know if you'd like to avoid circular dependencies in some other way

### CODE REVIEW

**Comment by Sand1929** [comment]
Nah, a runs module makes sense to me

**Comment by montaguegabe** [comment]
This is working, but doesn't just like when the "run" command is run from the CLI, the output of the pipeline run is not actually displayed.  Is this OK or should we change this?

**Comment by Sand1929** [comment]
What happens instead?

**Comment by montaguegabe** [comment]
It outputs this:
```
Type what do you want to do: Run the program called "stripe_list"
Preparing to run program stripe_list
Running program...
Going to https://stripe.com/newsroom/news
Scraping data in the format [{'title': 'str', 'link': 'link'}]
Done.
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ The program "stripe_list" has successfully run and returned data. If you need any help with the output or require further       │
│ actions, please let me know!                                                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Reply or type Q to end: 
```

**Comment by Sand1929** [comment]
Hmm, yeah at the very least it should probably print out the data

**Comment by montaguegabe** [comment]
I could have the CLI command display output, the assistant display output, and/or every invocation of `run` display output

**Comment by montaguegabe** [comment]
Right now with the last commit any time run is called (even within python), the JSON is output to the console, which results in an absolute wall of text (I didn't prettify it or it would be even longer).  When using the assistant, you can actually get the assistant to tell you what the result is.  Sometimes it does this automatically, for instance the second time I ran the request the assistant told me:

```
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ The program "stripe_list" has been successfully run. Here are some headlines from Stripe's newsroom:                            │
│                                                                                                                                 │
│ 1. "Stripe and JCB expand access to Japan’s growing ecommerce market" -                                                         │
│ [Link](https://stripe.com/newsroom/news/stripe-and-jcb-partnership-expansion)                                                   │
│ 2. "Stripe Tour Singapore showcases tools to help businesses expand globally" -                                                 │
│ [Link](https://stripe.com/newsroom/news/stripe-tour-singapore-2023)                                                             │
│ 3. "A decade of growth sees Irish businesses process more than €20 billion on Stripe" -                                         │
│ [Link](https://stripe.com/newsroom/news/ten-years-in-ireland)                                                                   │
│ 4. "Stripe launches the biggest set of upgrades yet for its optimized checkout suite" -                                         │
│ [Link](https://stripe.com/newsroom/news/optimized-checkout-suite)                                                               │
│ 5. "Stripe deepens product investment in Australia with unified commerce and finance automation" -                              │
│ [Link](https://stripe.com/newsroom/news/au-product-momentum)                                                                    │
│                                                                                                                                 │
│ ...and many more. The automation scraped a list of articles with their titles and links to the full content. If you require     │
│ more information or other assistance, feel free to ask.                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by montaguegabe** [comment]
Another issue is that it feels weird to type `parsagon create` in order to run a pipeline when you're not creating it.  Maybe the assistant should be triggered by just `parsagon`?  Also do we want the assistant to be able to list existing pipelines in the event that the name is incorrect and for other use cases?

**Comment by montaguegabe** [comment]
Right now, this tested PR implements functionality (minus assistant tweaks, which I will put in another PR):
- Adds ability to run via the assistant
- Assistant is invoked via `parsagon` (no subcommand)
- `parsagon create` is the old functionality.
  - I made it's import back into `import parsagon` then `parsagon.create`

**Comment by montaguegabe** [comment]
Rebased

**Comment by montaguegabe** [comment]
Ok this is tested and working alongside the PR in the -gpt repo

**Pull request merged**
